name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: {% raw %}${{ toJson(github) }}{% endraw %}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Publish
        env:
          FLIT_USERNAME: {% raw %}${{ secrets.FLIT_USERNAME }}{% endraw %}
          FLIT_PASSWORD: {% raw %}${{ secrets.FLIT_PASSWORD }}{% endraw %}
        run: bash scripts/publish.sh
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: {% raw %}${{ toJson(github) }}{% endraw %}
        run: echo "$GITHUB_CONTEXT"
