name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

      - name: Install flit and tox-related libs
        run: |
          python -m pip install --upgrade pip
          pip install flit tox tox-gh-actions

      - name: Install dependencies
        run: flit install --symlink

      - name: Test
        run: tox

      - name: Upload coverage
        uses: codecov/codecov-action@v1
